# Generated by @natalia/native-terminal — do not edit.
# Sources this package's zsh shell integration. Generated because zsh has no
# --rcfile: it reads $ZDOTDIR/.zshrc, and neither $0 (the shell's own name)
# nor $PWD (wherever the pane started) locates a sibling file.
builtin . "E:\\Development\\natalia-cli\\packages\\plugins\\native-terminal\\src\\shell-integration-zsh.sh"
