/**
 * Build the Windows installer inputs, or the installer itself when a tool is here.
 *
 * This is the step between "a release directory" and "a user double-clicks
 * Setup.exe". Both container formats — Inno Setup and MSIX/WiX — want the same
 * facts in different shapes, and the previous step already computed those facts
 * (`planWindowsInstall`). So this file renders them and hands them to whichever
 * tool is actually installed:
 *
 *   Inno Setup   a `.iss` script: `[Files]` from the derived tree, `[Icons]` for
 *                the Start Menu entry, `[UninstallDelete]`/registry values for the
 *                Apps & features row
 *   WiX/MSIX     a `.wxs` fragment with the same files and a `MajorUpgrade` bound
 *                to the upgrade code, so 1.2 replaces 1.1
 *
 * Neither compiler is guaranteed on the machine doing the build, so the rendered
 * input is the deliverable and a missing tool degrades to "script written,
 * compile it where the tool is". That is the same contract the macOS iconset and
 * the dmg staging already use: the artifact a Mac needs is produced anywhere; the
 * one-tool-only step is named rather than faked.
 */
import { existsSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { mkdir, rm, writeFile } from "node:fs/promises";
import {
  planWindowsInstall,
  type WindowsInstallPlan,
} from "./windows-install-plan";

export type BuildWindowsInstallerOptions = {
  releaseDir: string;
  outDir: string;
  appName?: string;
  publisher?: string;
  version?: string;
  installDirName?: string;
  icon?: string;
  /** The format to render. `both` writes one of each. */
  format?: "inno" | "wix" | "both";
  /** An existing plan, to skip re-deriving it. */
  plan?: WindowsInstallPlan;
  /**
   * An optional signing command Inno runs over the built binaries, e.g.
   * `signtool sign /a $f`. Absent means unsigned — which is the project's
   * situation and must stay possible: an unsigned installer is a warning, while
   * an unsigned MSIX package will not install at all.
   */
  signTool?: string;
};

export type WindowsInstallerArtifacts = {
  plan: WindowsInstallPlan;
  outDir: string;
  /** The Inno Setup script, when requested. */
  iss?: string;
  /** The WiX fragment, when requested. */
  wxs?: string;
  /** True when a compiler ran and produced the actual installer. */
  compiled: boolean;
  /** The compiler's output, when one ran. */
  installer?: string;
};

/** The Inno Setup pragmas a normal application declares. */
function innoPragmas(plan: WindowsInstallPlan, signTool?: string): string[] {
  return [
    "; Generated by scripts/build-windows-installer.ts — do not edit.",
    `#define MyAppName "${plan.appName}"`,
    `#define MyAppVersion "${plan.version}"`,
    `#define MyAppPublisher "${plan.publisher}"`,
    `#define MyAppExeName "${plan.shortcut.targetRelative}"`,
    `#define MyAppInstallDir "${plan.installDirName}"`,
    "",
    "[Setup]",
    `AppId={{${plan.uninstall.upgradeCode}}`,
    `AppName={#MyAppName}`,
    `AppVersion={#MyAppVersion}`,
    `AppPublisher={#MyAppPublisher}`,
    `DefaultDirName={autopf}\\{#MyAppInstallDir}`,
    `DefaultGroupName={#MyAppName}`,
    // An uninstaller the shell can find: without it "Apps & features" has a row
    // with no way out.
    "Uninstallable=yes",
    "CreateUninstallRegkey=yes",
    `UninstallDisplayName={#MyAppName} {#MyAppVersion}`,
    `UninstallDisplayIcon={app}\\${plan.shortcut.iconRelative ?? "app.ico"}`,
    "OutputDir=.",
    `OutputBaseFilename=Setup-{#MyAppName}-${plan.version}`,
    "Compression=lzma2",
    "SolidCompression=yes",
    "WizardStyle=modern",
    // Per-machine by default: the app lands in Program Files for every user of
    // the machine, which is what a normal application does.
    "PrivilegesRequired=admin",
    // Inno substitutes $f with each file it signs. A missing line is the honest
    // default: this project has no certificate, and a build that pretended
    // otherwise would fail on a machine that does.
    ...(signTool ? [`SignTool=${signTool}`] : []),
    "",
  ];
}

function innoFiles(plan: WindowsInstallPlan): string[] {
  return [
    "[Files]",
    // One line per derived file, so a release that gains a plugin cannot produce
    // an installer that drops it.
    ...plan.files.map(
      (file) =>
        `Source: "${file.source}"; DestDir: "{app}\\${
          file.target.includes("\\")
            ? file.target.slice(0, file.target.lastIndexOf("\\"))
            : "."
        }"; DestName: "${file.target.slice(file.target.lastIndexOf("\\") + 1)}"; Flags: ignoreversion`,
    ),
    "",
  ];
}

function innoIcons(plan: WindowsInstallPlan): string[] {
  return [
    "[Icons]",
    // The Start Menu entry. `Name` is what the user sees; `Filename` is what runs.
    `Name: "autoprograms\\{#MyAppName}"; Filename: "{app}\\${plan.shortcut.targetRelative}"; WorkingDir: "{app}"${
      plan.shortcut.iconRelative
        ? `; IconFilename: "{app}\\${plan.shortcut.iconRelative}"`
        : ""
    }`,
    "",
    // The uninstall entry, beside the app's own entry.
    `Name: "autoprograms\\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"`,
    "",
  ];
}

function innoRegistry(plan: WindowsInstallPlan): string[] {
  return [
    "[Registry]",
    // The Apps & features row. These values are what the shell reads; a missing
    // DisplayVersion shows as an unversioned entry that cannot be upgraded.
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "DisplayName"; ValueData: "{#MyAppName} {#MyAppVersion}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "Publisher"; ValueData: "{#MyAppPublisher}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "DisplayVersion"; ValueData: "{#MyAppVersion}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "InstallLocation"; ValueData: "{app}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: dword; ValueName: "EstimatedSize"; ValueData: "${plan.uninstall.estimatedSizeKB}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "UninstallString"; ValueData: """{uninstallexe}"""`,
    "",
    "[Code]",
    "// THE DESIGN, decided with the user, not assumed:",
    "//",
    "// 1. The app's data stays in the INSTALL FOLDER. Data travelling with the",
    "//    program is deliberate — the folder is portable, and moving it moves the",
    '//    data. That is not a defect and it is not to be "fixed" by relocating',
    "//    it to %LOCALAPPDATA%.",
    "//",
    "// 2. Uninstalling therefore has two possible behaviours, and the one chosen",
    "//    is: ASK, defaulting to KEEP. A plain uninstall leaves the user's model",
    "//    configuration, sessions and checkpoints alone; a user who wants them",
    "//    gone says so. Never delete them silently.",
    "//",
    "// 3. When they are kept, SAY SO, with the exact paths. Leaving files behind",
    "//    without telling anyone is what produced the complaint this fixes.",
    "//",
    "// There are TWO roots, and a version that cleaned only one of them is what",
    "// left `.natalia` behind after a run of the uninstaller:",
    "//   {app}\\.natalia      the config home. It is CWD-relative",
    "//                        (packages/hosts/platform/src/store-paths.ts), and",
    "//                        the launcher starts the runtime with the install",
    "//                        folder as CWD, so it lands INSIDE the install.",
    "//   {userprofile}\\.natalia  the per-user stores, sessions, logs and vault",
    "//                        (store-paths.ts walks from homedir()).",
    "//",
    "// A wizard page was the first attempt and it was WRONG, which is worth",
    "// recording because the failure was silent and ugly: it called a procedure",
    "// named `InitializeWizardUninstall`, which is not an Inno event at all (the",
    "// uninstaller's real hook is `InitializeUninstall`). The page was never",
    "// built, the variable holding it stayed nil, and `CurUninstallStepChanged`",
    "// then called a method on that nil object — Inno's Pascal runtime surfaces",
    "// that as `Runtime error: Could not call proc.`, so every uninstall died at",
    "// the very last step with a red X and no explanation. A wizard page is not",
    "// available on the uninstall side anyway. Hence a message box.",
    "var",
    "  KeepData: Boolean;",
    "",
    "function InitializeUninstall(): Boolean;",
    "var",
    "  Answer: Integer;",
    "begin",
    "  KeepData := True;",
    "  Answer := SuppressibleMsgBox(" +
      "'Natalia keeps its data in two places:' #13#10 #13#10 " +
      "'  ' + ExpandConstant('{app}') + '\\.natalia' #13#10 " +
      "'      the configuration home: your model settings, sessions, checkpoints' #13#10 #13#10 " +
      "'  ' + ExpandConstant('{userprofile}') + '\\.natalia' #13#10 " +
      "'      the per-user stores, sessions, logs and object vault' #13#10 #13#10 " +
      "'Delete them as well as the program?' #13#10 #13#10 " +
      "'Yes    = delete them' #13#10 " +
      "'No     = keep them (recommended)' #13#10 " +
      "'Cancel = do not uninstall',",
    "    mbConfirmation, MB_YESNOCANCEL or MB_DEFBUTTON2, IDNO);",
    "  if Answer = IDCANCEL then",
    "  begin",
    "    Result := False;",
    "    Exit;",
    "  end;",
    "  KeepData := (Answer = IDNO);",
    "  Result := True;",
    "end;",
    "",
    "procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);",
    "var",
    "  Target: String;",
    "  Failed: Boolean;",
    "  Kept: String;",
    "begin",
    "  if CurUninstallStep <> usPostUninstall then",
    "    Exit;",
    "  Failed := False;",
    "  Kept := '';",
    "  if not KeepData then",
    "  begin",
    "    // The user said yes: both roots go. The config home first — it is the",
    "    // one that holds the model configuration, and it is the one that lands",
    "    // inside the install folder because the launcher runs the runtime with",
    "    // the install folder as its working directory.",
    "    Target := ExpandConstant('{app}\\.natalia');",
    "    if DirExists(Target) then",
    "    begin",
    "      if not DelTree(Target, True, True, True) then",
    "      begin",
    "        Failed := True;",
    "        Log('Natalia uninstaller: could not fully remove ' + Target +",
    "            ' (the application may still be running)');",
    "        Kept := Kept + '  ' + Target + #13#10;",
    "      end",
    "      else",
    "        Log('Natalia uninstaller: removed ' + Target);",
    "    end;",
    "    Target := ExpandConstant('{userprofile}\\.natalia');",
    "    if DirExists(Target) then",
    "    begin",
    "      if not DelTree(Target, True, True, True) then",
    "      begin",
    "        Failed := True;",
    "        Log('Natalia uninstaller: could not fully remove ' + Target +",
    "            ' (the application may still be running)');",
    "        Kept := Kept + '  ' + Target + #13#10;",
    "      end",
    "      else",
    "        Log('Natalia uninstaller: removed ' + Target);",
    "    end;",
    "    // The plugin store and the window host's user-data dir. Neither is user",
    "    // content — one is downloaded plugins, the other is CEF's profile — so",
    "    // they follow the same answer rather than being asked about separately.",
    "    Target := ExpandConstant('{app}\\plugin-store');",
    "    if DirExists(Target) then",
    "      if not DelTree(Target, True, True, True) then",
    "        Log('Natalia uninstaller: could not fully remove ' + Target);",
    "    Target := ExpandConstant('{app}\\user-data');",
    "    if DirExists(Target) then",
    "      if not DelTree(Target, True, True, True) then",
    "        Log('Natalia uninstaller: could not fully remove ' + Target);",
    "  end",
    "  else",
    "  begin",
    "    // The user said no, so say where their data is. Silence is what made " +
      "this",
    "    // look like a bug: files survived and nobody was told they had.",
    "    if DirExists(ExpandConstant('{app}\\.natalia')) then",
    "      Kept := Kept + '  ' + ExpandConstant('{app}\\.natalia') + #13#10;",
    "    if DirExists(ExpandConstant('{userprofile}\\.natalia')) then",
    "      Kept := Kept + '  ' + ExpandConstant('{userprofile}\\.natalia') + #13#10;",
    "  end;",
    "  if KeepData and (Kept <> '') then",
    "    SuppressibleMsgBox('Natalia has been uninstalled.' #13#10 #13#10 " +
      "      'Your data was left in place:' #13#10 #13#10 + Kept + #13#10 " +
      "      'Delete those folders by hand if you do not need them.',",
    "      mbInformation, MB_OK, IDOK);",
    "  if Failed then",
    "    SuppressibleMsgBox('Natalia was uninstalled, but some of its data could not be removed (the application may still be running). You can delete those folders by hand, or close Natalia and run the uninstaller again.',",
    "      mbError, MB_OK, IDOK);",
    "end;",
    "",
  ];
}

/** Render the plan as an Inno Setup script. */
export function renderInnoScript(
  plan: WindowsInstallPlan,
  signTool?: string,
): string {
  return [
    ...innoPragmas(plan, signTool),
    ...innoFiles(plan),
    ...innoIcons(plan),
    ...innoRegistry(plan),
    "[Run]",
    // Nothing. A user must never be told to run something after an install; the
    // app is started from the Start Menu entry, like every other application.
    "",
  ].join("\n");
}

/** Render the plan as a WiX fragment (the MSIX/WiX side of the choice). */
export function renderWixFragment(plan: WindowsInstallPlan): string {
  const componentLines = plan.files
    .map(
      (file) =>
        `      <File Source="${file.source}" Name="${file.target.slice(file.target.lastIndexOf("\\") + 1)}" />`,
    )
    .join("\n");
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">',
    `  <Product Id="*" UpgradeCode="{${plan.uninstall.upgradeCode}}" Name="${plan.appName}" Version="${plan.version}" Language="1033" Manufacturer="${plan.publisher}">`,
    '    <Package InstallerVersion="500" Compressed="yes" />',
    "    <!-- A later version upgrades this one rather than installing beside it. -->",
    '    <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />',
    '    <MediaTemplate EmbedCab="yes" />',
    `    <Directory Id="TARGETDIR" Name="SourceDir">`,
    `      <Directory Id="ProgramFiles64Folder">`,
    `        <Directory Id="INSTALLFOLDER" Name="${plan.installDirName}">`,
    '          <Component Id="MainComponent" Guid="*">',
    componentLines,
    "            <!-- The Start Menu entry, and the Apps & features row. -->",
    `            <Shortcut Id="StartMenuShortcut" Directory="ProgramMenuDir" Name="${plan.appName}" WorkingDirectory="INSTALLFOLDER" Advertise="no" />`,
    `            <RemoveFile Id="RemoveStartMenuShortcut" Directory="ProgramMenuDir" Name="${plan.appName}" On="uninstall" />`,
    `            <RegistryValue Root="HKLM" Key="Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${plan.appName}" Name="DisplayVersion" Type="string" Value="${plan.version}" KeyPath="yes" />`,
    "          </Component>",
    "        </Directory>",
    "      </Directory>",
    "    </Directory>",
    '    <Feature Id="MainFeature" Title="Natalia" Level="1">',
    '      <ComponentRef Id="MainComponent" />',
    "    </Feature>",
    "  </Product>",
    "</Wix>",
    "",
  ].join("\n");
}

export async function buildWindowsInstallerInputs(
  options: BuildWindowsInstallerOptions,
): Promise<WindowsInstallerArtifacts> {
  const outDir = resolve(options.outDir);
  const format = options.format ?? "both";
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const plan =
    options.plan ??
    (await planWindowsInstall({
      releaseDir: options.releaseDir,
      appName: options.appName,
      publisher: options.publisher,
      version: options.version,
      installDirName: options.installDirName,
      icon: options.icon,
    }));

  const result: WindowsInstallerArtifacts = {
    plan,
    outDir,
    compiled: false,
  };
  // The inputs are written BESIDE THE SOURCES, in the release directory, not in
  // outDir. The Source lines are release-relative on purpose — an absolute path
  // bakes the build machine in (a test pins the relativity, learned from a real
  // 91 MB release) — so the script compiles exactly where it is written and
  // nowhere else. Writing it to outDir instead produced a delivered .iss that
  // failed with "Source file does not exist" on the very Windows host the
  // message told to compile it. The COMPILED installer is what lands in outDir.
  if (format === "inno" || format === "both") {
    const iss = join(options.releaseDir, `${plan.installDirName}.iss`);
    await writeFile(iss, renderInnoScript(plan, options.signTool), "utf8");
    result.iss = iss;
  }
  if (format === "wix" || format === "both") {
    const wxs = join(options.releaseDir, `${plan.installDirName}.wxs`);
    await writeFile(wxs, renderWixFragment(plan), "utf8");
    result.wxs = wxs;
  }

  // Compiling needs the tool, and only Windows has one natively. A build
  // anywhere else produces the inputs, which is the part a Windows build needs.
  // NATALIA_ISCC names a compiler for a host that has one under another name —
  // wine's ISCC on Linux, say — so the compile step is reachable without
  // pretending the platform has the tool natively.
  const inno = Bun.which("ISCC") ?? resolveEnvCompiler("NATALIA_ISCC");
  if (inno && result.iss) {
    const installer = join(outDir, `Setup-${plan.appName}-${plan.version}.exe`);
    const run = Bun.spawnSync([inno, `/O${outDir}`, result.iss], {
      stdout: "inherit",
      stderr: "inherit",
    });
    if (run.exitCode === 0) {
      result.compiled = true;
      result.installer = installer;
    }
  }
  const candle = Bun.which("candle") ?? resolveEnvCompiler("NATALIA_CANDLE");
  if (candle && result.wxs) {
    const obj = join(outDir, `${plan.installDirName}.wixobj`);
    const run = Bun.spawnSync([candle, result.wxs, "-o", obj, "-arch", "x64"], {
      stdout: "inherit",
      stderr: "inherit",
    });
    if (run.exitCode === 0) result.compiled = true;
  }
  return result;
}

/** A compiler named by an environment variable, or null when unset. */
function resolveEnvCompiler(variable: string): string | null {
  const named = process.env[variable];
  if (!named) return null;
  return Bun.which(named);
}

/**
 * The newest windows-x64 release tree under a base directory, or undefined.
 *
 * "Newest" is by BUILD TIME, not by name: sorting the paths lexicographically
 * picked a directory called `uninst` over `0.0.0-m13` (measured — a leftover
 * scratch release hijacked a real installer build and packed the wrong tree),
 * and version-shaped directory names do not sort as versions anyway.
 */
export async function newestRelease(
  base: string,
  hostTriple: string,
): Promise<string | undefined> {
  if (!existsSync(base)) return undefined;
  const candidates: string[] = [];
  for await (const version of new Bun.Glob("*/").scan({
    cwd: base,
    onlyFiles: false,
  })) {
    const dir = join(base, version, hostTriple);
    if (existsSync(dir)) candidates.push(dir);
  }
  return candidates
    .sort((a, b) => statSync(a).mtimeMs - statSync(b).mtimeMs)
    .at(-1);
}

/** True when the rendered script declares a Start Menu entry and an uninstaller. */
export function scriptDeclaresEntryPoints(text: string): boolean {
  return (
    text.includes("[Icons]") &&
    text.includes("[Registry]") &&
    text.includes("Uninstallable=yes")
  );
}
