/**
 * Build the Windows installer inputs, or the installer itself when a tool is here.
 *
 * This is the step between "a release directory" and "a user double-clicks
 * Setup.exe". Both container formats — Inno Setup and MSIX/WiX — want the same
 * facts in different shapes, and the previous step already computed those facts
 * (`planWindowsInstall`). So this file renders them and hands them to whichever
 * tool is actually installed:
 *
 *   Inno Setup   a `.iss` script: `[Files]` from the derived tree, `[Icons]` for
 *                the Start Menu entry, `[UninstallDelete]`/registry values for the
 *                Apps & features row
 *   WiX/MSIX     a `.wxs` fragment with the same files and a `MajorUpgrade` bound
 *                to the upgrade code, so 1.2 replaces 1.1
 *
 * Neither compiler is guaranteed on the machine doing the build, so the rendered
 * input is the deliverable and a missing tool degrades to "script written,
 * compile it where the tool is". That is the same contract the macOS iconset and
 * the dmg staging already use: the artifact a Mac needs is produced anywhere; the
 * one-tool-only step is named rather than faked.
 */
import { existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { mkdir, rm, writeFile } from "node:fs/promises";
import {
  planWindowsInstall,
  type WindowsInstallPlan,
} from "./windows-install-plan";

export type BuildWindowsInstallerOptions = {
  releaseDir: string;
  outDir: string;
  appName?: string;
  publisher?: string;
  version?: string;
  installDirName?: string;
  icon?: string;
  /** The format to render. `both` writes one of each. */
  format?: "inno" | "wix" | "both";
  /** An existing plan, to skip re-deriving it. */
  plan?: WindowsInstallPlan;
};

export type WindowsInstallerArtifacts = {
  plan: WindowsInstallPlan;
  outDir: string;
  /** The Inno Setup script, when requested. */
  iss?: string;
  /** The WiX fragment, when requested. */
  wxs?: string;
  /** True when a compiler ran and produced the actual installer. */
  compiled: boolean;
  /** The compiler's output, when one ran. */
  installer?: string;
};

/** The Inno Setup pragmas a normal application declares. */
function innoPragmas(plan: WindowsInstallPlan): string[] {
  return [
    "; Generated by scripts/build-windows-installer.ts — do not edit.",
    `#define MyAppName "${plan.appName}"`,
    `#define MyAppVersion "${plan.version}"`,
    `#define MyAppPublisher "${plan.publisher}"`,
    `#define MyAppExeName "${plan.shortcut.targetRelative}"`,
    `#define MyAppInstallDir "${plan.installDirName}"`,
    "",
    "[Setup]",
    `AppId={{${plan.uninstall.upgradeCode}}`,
    `AppName={#MyAppName}`,
    `AppVersion={#MyAppVersion}`,
    `AppPublisher={#MyAppPublisher}`,
    `DefaultDirName={autopf}\\{#MyAppInstallDir}`,
    `DefaultGroupName={#MyAppName}`,
    // An uninstaller the shell can find: without it "Apps & features" has a row
    // with no way out.
    "Uninstallable=yes",
    "CreateUninstallRegkey=yes",
    `UninstallDisplayName={#MyAppName} {#MyAppVersion}`,
    `UninstallDisplayIcon={app}\\${plan.shortcut.iconRelative ?? "app.ico"}`,
    "OutputDir=.",
    `OutputBaseFilename=Setup-{#MyAppName}-${plan.version}`,
    "Compression=lzma2",
    "SolidCompression=yes",
    "WizardStyle=modern",
    // Per-machine by default: the app lands in Program Files for every user of
    // the machine, which is what a normal application does.
    "PrivilegesRequired=admin",
    "",
  ];
}

function innoFiles(plan: WindowsInstallPlan): string[] {
  return [
    "[Files]",
    // One line per derived file, so a release that gains a plugin cannot produce
    // an installer that drops it.
    ...plan.files.map(
      (file) =>
        `Source: "${file.source}"; DestDir: "{app}\\${
          file.target.includes("\\")
            ? file.target.slice(0, file.target.lastIndexOf("\\"))
            : "."
        }"; DestName: "${file.target.slice(file.target.lastIndexOf("\\") + 1)}"; Flags: ignoreversion`,
    ),
    "",
  ];
}

function innoIcons(plan: WindowsInstallPlan): string[] {
  return [
    "[Icons]",
    // The Start Menu entry. `Name` is what the user sees; `Filename` is what runs.
    `Name: "autoprograms\\{#MyAppName}"; Filename: "{app}\\${plan.shortcut.targetRelative}"; WorkingDir: "{app}"${
      plan.shortcut.iconRelative
        ? `; IconFilename: "{app}\\${plan.shortcut.iconRelative}"`
        : ""
    }`,
    "",
    // The uninstall entry, beside the app's own entry.
    `Name: "autoprograms\\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"`,
    "",
  ];
}

function innoRegistry(plan: WindowsInstallPlan): string[] {
  return [
    "[Registry]",
    // The Apps & features row. These values are what the shell reads; a missing
    // DisplayVersion shows as an unversioned entry that cannot be upgraded.
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "DisplayName"; ValueData: "{#MyAppName} {#MyAppVersion}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "Publisher"; ValueData: "{#MyAppPublisher}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "DisplayVersion"; ValueData: "{#MyAppVersion}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "InstallLocation"; ValueData: "{app}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: dword; ValueName: "EstimatedSize"; ValueData: "${plan.uninstall.estimatedSizeKB}"`,
    `Root: HKLM; Subkey: "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{{${plan.uninstall.upgradeCode}}}_is1"; ValueType: string; ValueName: "UninstallString"; ValueData: """{uninstallexe}"""`,
    "",
    "[Code]",
    "// A second launch focuses the running window instead of starting a copy;",
    "// the single-instance lock (instance.ts) is the other half of that.",
    "",
  ];
}

/** Render the plan as an Inno Setup script. */
export function renderInnoScript(plan: WindowsInstallPlan): string {
  return [
    ...innoPragmas(plan),
    ...innoFiles(plan),
    ...innoIcons(plan),
    ...innoRegistry(plan),
    "[Run]",
    // Nothing. A user must never be told to run something after an install; the
    // app is started from the Start Menu entry, like every other application.
    "",
  ].join("\n");
}

/** Render the plan as a WiX fragment (the MSIX/WiX side of the choice). */
export function renderWixFragment(plan: WindowsInstallPlan): string {
  const componentLines = plan.files
    .map(
      (file) =>
        `      <File Source="${file.source}" Name="${file.target.slice(file.target.lastIndexOf("\\") + 1)}" />`,
    )
    .join("\n");
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">',
    `  <Product Id="*" UpgradeCode="{${plan.uninstall.upgradeCode}}" Name="${plan.appName}" Version="${plan.version}" Language="1033" Manufacturer="${plan.publisher}">`,
    '    <Package InstallerVersion="500" Compressed="yes" />',
    "    <!-- A later version upgrades this one rather than installing beside it. -->",
    '    <MajorUpgrade DowngradeErrorMessage="A newer version is already installed." />',
    '    <MediaTemplate EmbedCab="yes" />',
    `    <Directory Id="TARGETDIR" Name="SourceDir">`,
    `      <Directory Id="ProgramFiles64Folder">`,
    `        <Directory Id="INSTALLFOLDER" Name="${plan.installDirName}">`,
    '          <Component Id="MainComponent" Guid="*">',
    componentLines,
    "            <!-- The Start Menu entry, and the Apps & features row. -->",
    `            <Shortcut Id="StartMenuShortcut" Directory="ProgramMenuDir" Name="${plan.appName}" WorkingDirectory="INSTALLFOLDER" Advertise="no" />`,
    `            <RemoveFile Id="RemoveStartMenuShortcut" Directory="ProgramMenuDir" Name="${plan.appName}" On="uninstall" />`,
    `            <RegistryValue Root="HKLM" Key="Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${plan.appName}" Name="DisplayVersion" Type="string" Value="${plan.version}" KeyPath="yes" />`,
    "          </Component>",
    "        </Directory>",
    "      </Directory>",
    "    </Directory>",
    '    <Feature Id="MainFeature" Title="Natalia" Level="1">',
    '      <ComponentRef Id="MainComponent" />',
    "    </Feature>",
    "  </Product>",
    "</Wix>",
    "",
  ].join("\n");
}

export async function buildWindowsInstallerInputs(
  options: BuildWindowsInstallerOptions,
): Promise<WindowsInstallerArtifacts> {
  const outDir = resolve(options.outDir);
  const format = options.format ?? "both";
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const plan =
    options.plan ??
    (await planWindowsInstall({
      releaseDir: options.releaseDir,
      appName: options.appName,
      publisher: options.publisher,
      version: options.version,
      installDirName: options.installDirName,
      icon: options.icon,
    }));

  const result: WindowsInstallerArtifacts = {
    plan,
    outDir,
    compiled: false,
  };
  if (format === "inno" || format === "both") {
    const iss = join(outDir, `${plan.installDirName}.iss`);
    await writeFile(iss, renderInnoScript(plan), "utf8");
    result.iss = iss;
  }
  if (format === "wix" || format === "both") {
    const wxs = join(outDir, `${plan.installDirName}.wxs`);
    await writeFile(wxs, renderWixFragment(plan), "utf8");
    result.wxs = wxs;
  }

  // Compiling needs the tool, and only Windows has it. A build anywhere else
  // produces the inputs, which is the part a Windows build needs.
  const inno = Bun.which("ISCC");
  if (inno && result.iss) {
    const installer = join(outDir, `Setup-${plan.appName}-${plan.version}.exe`);
    const run = Bun.spawnSync([inno, `/O${outDir}`, result.iss], {
      stdout: "inherit",
      stderr: "inherit",
    });
    if (run.exitCode === 0) {
      result.compiled = true;
      result.installer = installer;
    }
  }
  const candle = Bun.which("candle");
  if (candle && result.wxs) {
    const obj = join(outDir, `${plan.installDirName}.wixobj`);
    const run = Bun.spawnSync([candle, result.wxs, "-o", obj, "-arch", "x64"], {
      stdout: "inherit",
      stderr: "inherit",
    });
    if (run.exitCode === 0) result.compiled = true;
  }
  return result;
}

/** True when the rendered script declares a Start Menu entry and an uninstaller. */
export function scriptDeclaresEntryPoints(text: string): boolean {
  return (
    text.includes("[Icons]") &&
    text.includes("[Registry]") &&
    text.includes("Uninstallable=yes")
  );
}
