# Generated by @natalia/native-terminal — do not edit.
# Sources this package's zsh shell integration. It is generated because the
# path must be absolute for this checkout: zsh sources $ZDOTDIR/.zshrc with
# $0 set to the shell name and $PWD left wherever the pane started, so a
# relative path would silently load nothing.
builtin . "/home/aquama/Development/Natalia_Project/natalia-cli/packages/plugins/native-terminal/src/shell-integration-zsh.sh"
